global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'self'
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'isu'
    scrape_interval: 1s
    static_configs:
      - targets: ['isu-1:9100', 'isu-2:9100', 'isu-3:9100', 'isu-4:9100']
  - job_name: 'isu_bench'
    static_configs:
      - targets: ['isu-bench:9100']
